### ISSUE TITLE
Problem adding Jakarta Dependency in POM

### ISSUE THREAD

**Issue by antonio031** [IMarcelF/IGRP-Framework#1805]
Expected Behavior
When connecting the application with the database, the Jakarta dependency should be added automatically in POM. This addition is crucial for enabling the listing of all tables in the database, allowing users to visualize and interact with the database tables seamlessly.

Current Behavior
The Jakarta dependency is not automatically added when establishing a connection to the database, resulting in the inability to list tables in the database.

**Comment by NOSiopen** [comment]
Hello

I think the problem is a reload server and the use of lowercase for the names of the tables, if you have used postgres...

PS: for the reload part, we have added this commit to resolve the automatic _**reloadOnUpdate**_ if you are using mvn package tomee:run - https://github.com/NOSiCode-CV/IGRP-Framework/commit/58c019f177db13f916a19417babe960cf4516100

Please comment if you continued with a problem, and contact us.

**Comment by NOSiopen** [comment]
Bom vou fechar o no issue e se for abres de novo...
